// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4gv1pmWkOMqRMM5WMJP3QqEasrcs-0lM',
    appId: '1:986164924058:web:056c8cd599df76ba46d923',
    messagingSenderId: '986164924058',
    projectId: 'dekrapfe',
    authDomain: 'dekrapfe.firebaseapp.com',
    storageBucket: 'dekrapfe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMZT9MSgCu9GyVgHW0GMwAEWlKUBPgWOk',
    appId: '1:986164924058:android:e056918709b4bcd246d923',
    messagingSenderId: '986164924058',
    projectId: 'dekrapfe',
    storageBucket: 'dekrapfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdyMW2cfNhlW8kYg_lXya2eb2fp-Slb6A',
    appId: '1:986164924058:ios:07abae09928350a246d923',
    messagingSenderId: '986164924058',
    projectId: 'dekrapfe',
    storageBucket: 'dekrapfe.appspot.com',
    iosBundleId: 'com.dekrapfe.dekrapfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdyMW2cfNhlW8kYg_lXya2eb2fp-Slb6A',
    appId: '1:986164924058:ios:07abae09928350a246d923',
    messagingSenderId: '986164924058',
    projectId: 'dekrapfe',
    storageBucket: 'dekrapfe.appspot.com',
    iosBundleId: 'com.dekrapfe.dekrapfe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4gv1pmWkOMqRMM5WMJP3QqEasrcs-0lM',
    appId: '1:986164924058:web:47fe25440508b37346d923',
    messagingSenderId: '986164924058',
    projectId: 'dekrapfe',
    authDomain: 'dekrapfe.firebaseapp.com',
    storageBucket: 'dekrapfe.appspot.com',
  );
}
